name: mav9

recipe: pantheon

config:
  framework: drupal8
  site: mav9
  id: 914e5154-7c96-4fef-9d8d-317ff8e70798
  xdebug: true
  config:
    php: config/php.ini
  # Disable the SOLR index
  index: false
  # Disable the VARNISH edge
  edge: false
  # Disable the REDIS cache
  cache: false

services:
  database:
    type: mariadb:10.5
    portforward: 32825
  appserver:
    run_as_root:
      - apt-get update
      - curl -fsSL https://deb.nodesource.com/setup_lts.x | bash -
      - apt-get install -y nodejs
      - npm install -g gulp-cli gulp sass

tooling:
  drush:
    service: appserver
    env:
      DRUSH_OPTIONS_URI: "https://mav9.lndo.site"
  npm:
    service: appserver
  node:
    service: appserver
  gulp:
    service: appserver
  sass:
    service: appserver
