mav_jitsi.settings:
  type: config_object
  label: 'Jitsi settings'
  mapping:
    mav_jitsi_domain:
      type: string
      label: 'Domain Jitsi'
    mav_jitsi_view:
      type: string
      label: 'Full screen'
    mav_jitsi_window_width:
      type: float
      label: 'Jitsi window width'

# Default value.
field.value.mav_jitsi_conference:
  type: mapping
  label: Default value
  mapping:
    jitsi_conf:
      type: string
      label: jitsi conf
# Field widget.
field.widget.settings.mav_jitsi_conference:
  type: mapping
  label: jitsi conf widget settings
  mapping:
    domain:
      type: string
      label: domain
# Field formatter.
field.formatter.settings.mav_jitsi_conference_default:
  type: mapping
  label: Example formatter settings
  mapping:
    domain:
      type: string
      label: domain